---
abstract: 'Extend Plack::Middleware::Debug with Redis panels'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  Test::More: 0.98
  Test::Pod: 1.22
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-Redis
no_index:
  directory:
    - t
    - inc
requires:
  Plack::Middleware::Debug: 0
  Redis: 1.955
  perl: 5.010001
  strict: 0
resources:
  bugtracker: https://github.com/Wu-Wu/Plack-Middleware-Debug-Redis/issues
  repository: https://github.com/Wu-Wu/Plack-Middleware-Debug-Redis
version: 0.01
